version: "3.8"

services:
  chat-client:
    image: chat-client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - SIGNALING_SERVER_HOSTNAME=${NEXT_PUBLIC_SIGNALING_SERVER_HOSTNAME}
        - SIGNALING_SERVER_PORT=${NEXT_PUBLIC_SIGNALING_SERVER_PORT}
        - SIGNALING_SERVER_ENDPOINT=${NEXT_PUBLIC_SIGNALING_SERVER_ENDPOINT}
        - SIGNALING_SERVER_ENABLED=${NEXT_PUBLIC_SIGNALING_SERVER_ENABLED}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}

  chat-server:
    image: chat-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PORT=9000