version: "3.8"

services:
  chat-client:
    image: chat-client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - SIGNALING_SERVER_HOSTNAME=localhost
        - SIGNALING_SERVER_PORT=9000
        - SIGNALING_SERVER_ENDPOINT=/chat
        - SIGNALING_SERVER_ENABLED=true
        - CHAT_CLIENT_PORT=3000
        - NODE_ENV=development
    ports:
      - "3000:3000"

  chat-signalingserver:
    image: chat-signalingserver
    build:
      context: ./signalingserver
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - NODE_ENV=development
      - BEHIND_PROXY=false
      - SSL_ENABLE=false
      - SSL_KEY_PATH=
      - SSL_CERT_PATH=