version: "3.8"

services:
  chat-client:
    image: chat-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - chat-server
    environment:
      - NEXT_PUBLIC_SIGNAL_SERVER_HOSTNAME=chat-server
      - NEXT_PUBLIC_SIGNAL_SERVER_PORT=9000
      - NEXT_PUBLIC_SIGNAL_SERVER_ENDPOINT=/chat
      - PORT=3000

  chat-server:
    image: chat-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PORT=9000