import Head from 'next/head'
import {useRouter} from 'next/router'
import Connector from "../components/Connector";
import Connectee from "../components/Connectee";
import {useEffect, useState} from "react";

export default function Home() {
    const router = useRouter()
    const [encodedRemoteAddress, setEncodedRemoteAddress] = useState<string | undefined>(undefined)

    useEffect(() => {
        setEncodedRemoteAddress(getEncodedRemoteAddressFromUrl(router.asPath))
    })

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={"h-full"}>
                {encodedRemoteAddress ? <Connectee encodedRemoteAddress={encodedRemoteAddress}/> : <Connector/>}
            </main>
        </>
    )
}

function getEncodedRemoteAddressFromUrl(path: string) {
    const pathParts = path.split("#")
    return pathParts.length > 1 ? pathParts.pop() : undefined
}